"""add emailverification models

Revision ID: d1ff9d5c89b3
Revises: f0afe21788ec
Create Date: 2024-08-20 21:01:50.120771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ff9d5c89b3'
down_revision: Union[str, None] = 'f0afe21788ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verification', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('email_verification', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('email_verification', sa.Column('expiretion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint(None, 'email_verification', ['uuid'])
    op.create_foreign_key(None, 'email_verification', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_verification', type_='foreignkey')
    op.drop_constraint(None, 'email_verification', type_='unique')
    op.drop_column('email_verification', 'expiretion')
    op.drop_column('email_verification', 'created')
    op.drop_column('email_verification', 'user_id')
    # ### end Alembic commands ###
